---
- name: Deploy nginx
  shell: |
    sleep 20
    kubectl run nginx --image=nginx
    kubectl expose pod nginx --port=80 --type=NodePort

- name: Get port
  shell: |
    kubectl get svc nginx
  register: nginxResults

- name: debug
  debug: 
    var: nginxResults
    verbosity: 1

- name: save results
  connection: local
  local_action:
    module: copy
    content: "{{ nginxResults  }}"
    dest: ./nginx.out

- name: copy k8s config
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ./config
    flat: yes

